#!/bin/bash
# permission-edits

set -e

for d in "$@"; do
    find "${d}" \
        ! \( -group "${OHDSI_GID}" -a -perm -g+rwX \) \
        -exec chgrp "${OHDSI_GID}" -- {} \+ \
        -exec chmod g+rwX -- {} \+
    # setuid, setgid *on directories only*
    find "${d}" \
        \( -type d -a ! -perm -6000 \) \
        -exec chmod +6000 -- {} \+
done